services:

  db-master:
    image: mysql:8.0
    container_name: db-master
    restart: always
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-do-db=klinik_db
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE: klinik_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - dbnet

  db-slave:
    image: mysql:8.0
    container_name: db-slave
    restart: always
    command: >
      --server-id=2
      --read-only=1
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
    networks:
      - dbnet
    depends_on:
      - db-master

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    restart: always
    ports:
      - "3300:3300"
      - "8900:8900"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - dbnet
    depends_on:
      - db-master
      - db-slave

networks:
  dbnet:
    driver: bridge
